### ISSUE TITLE
Call For Contribution

### ISSUE THREAD

**Issue by sinfomicien** [sous-chefs/mariadb#100]
Hi dear community!

Since a while, i have less and less time to maintain this cookbook. For a lot of good reasons :)

At my job, i do less and less code... More and more management!
And at home, 2 children and 1 wife keep me occupied.

If you feel you wanna help me, i will let you manage the repository! Please write me in PM.

Thx to everybody!

**Comment by joerocklin** [comment]
Hey @sinfomicien - there doesn't seem to be a way to PM in github anymore. I can't promise a lot of time to help manage things, but could be another pair of eyes to review PRs and issues.

**Comment by jwmarshall** [comment]
Seems like you guys really need some help with this. I'm (for better or worse) getting more involved with mysql (specifically the mariadb variant) and I've been a chef user for 5+ years. I cant promise limitless cycles to work on this but I'd be more than happy to help out.

**Comment by sinfomicien** [comment]
Dear jwmarshall, you've been added as a collaborator for both the repository, and for the cookbook on supermarket! We need help, you're welcome if you want to ! :)
Thx a lot

**Comment by jwmarshall** [comment]
@sinfomicien I don't seem to have the ability to merge pull requests.

Edit: Nevermind I didn't realize I had to accept an invite.

**Comment by mjuszczak** [comment]
Chef needs an actively maintained MariaDB cookbook. Per a point @jcotton1123 made to me today, Puppet has a single MySQL module that works for MySQL, MariaDB, and (I assume) Percona.
But back in 2013, @sethvargo wrote on this ticket (https://tickets.opscode.com/browse/COOK-3487):

> ...while you are right that there are similarities between MariaDB and MySQL, they are not the same product. The inclusion of the Percona recipes are also of question, but the past is the past .
> Given the existing bloat in the MySQL cookbook, we think it is in the best interest for a community member who uses MariaDB to create and maintain an alternative community cookbook.

His points are valid.

I'm assuming this cookbook was that alternative community cookbook, and @sinfomicien, you've done a great job with this. There are currently 20 open issues and 19 open pull requests on this cookbook. We're using it for at least one customer, so I'm happy to request collaborator access (as would @jcotton1123, who recently opened a PR).

Does anyone have any thoughts on a solution to this issue? Should we all put effort into continuing to maintain this cookbook or are others finding alternatives I'm missing?

**Comment by sinfomicien** [comment]
Dear Matt & Jesse... You're welcome on the project :)
You've been invited as collaborator on the repo... And as collaborator on the supermarket!

**Comment by josephholsten** [comment]
@sinfomicien sounds like you've had the same idea we had. If there's anything https://github.com/chef-brigade/ can do to help, let us know. Especially happy to help with admin overhead, and we've got folks who are excited about contributing.

**Comment by sinfomicien** [comment]
@josephholsten : I always need help! To start, i give you access to the repo ! Will try to give you access to supermarket tomorrow... What's your preferred way of communication to go further ? Slack/Hangout, Skype, mail, other ? :)

**Comment by jwmarshall** [comment]
I must admit I've also fallen behind in helping. Unfortunately I have some (rather insane) deadlines approaching. I should be back in the swing of things mid-December though.

I think putting together a Slack team or something would be great for coordinating our efforts and discussing where we want to take the development of this cookbook.

**Comment by mjuszczak** [comment]
@jwmarshall Agreed. Or to @josephholsten's point, might make sense to put this cookbook under the management of chef-brigade? They already manage related cookbooks, like MongoDB and PostgreSQL. I'm happy to help maintain it either way.

**Comment by jwmarshall** [comment]
Im not familiar with those guys, and I don't believe I use any of their cookbooks, but I'm certainly not opposed. If they already have a communication stream as well maybe we should all join forces?

**Comment by mjuszczak** [comment]
@jwmarshall I am not familiar either; however, there seems to be some energy there. @sinfomicien, what would you prefer?

**Comment by JCotton1123** [comment]
I wish there was a better way to communicate then this...

We, the maintainers, need to be careful about versioning. I was looking at releasing a new 0.3.x version of the cookbook however master contains at least one set of breaking changes - adding a priority to the config file names (ex: innodb.cnf becomes 20-innodb.cnf). What is currently in master likely needs to be released as 1.x. I am going to cut a 0.3.x branch from the last 0.3.1 release and cherry-pick a few changes into it.

**Comment by josephholsten** [comment]
FYI: chef-brigade has been renamed to sous-chefs, and lives at https://github.com/sous-chefs

Currently we're working to put together some standards (just recommendations, really) and tooling to help. We're also about to start building some test infra for people to run test-kitchen on.

But don't feel like you're got to relinquish anything, we're happy to help no matter where the cookbook lives. Feel free to poke us in https://chefcommunity.slack.com/messages/sous-chefs/

**Comment by mjuszczak** [comment]
Anyone else have any thoughts?

**Comment by shoekstra** [comment]
We use this cookbook a fair amount internally and it would be a shame if it wasn't kept up to date. It looks like a few people have already put their hands up to help, but if still looking for someone I am happy to assist.

**Comment by josephholsten** [comment]
@sinfomicien I've gotten a request to fork this cookbook into sous-chefs so more people can have commit access. I'd really like to avoid that. Do you think you can get another person or two to have commit access? Or would you be okay with transferring this cookbook to sous-chefs?

I'm watching this thread, and would be happy to chat in the chef community slack or in chef IRC.

**Comment by josephholsten** [comment]
@sinfomicien sous-chefs have had a chat and put together this process for if we have to create a hard fork: https://github.com/sous-chefs/meta/blob/master/docs/forking.md

So we're going to wait until 2017-03-10 before letting anyone create a hard fork. I really hope to hear from you before then so we can avoid that.

To anyone wanting help getting their PRs tested, we've created a soft fork at https://github.com/sous-chefs/mariadb. We'd still like to see everything merged into the official mariadb cookbook, but we can work on integrating patches over there in the mean time.

**Comment by josephholsten** [comment]
well, I feel like a total jerk. apparently /I/ have a commit bit. Honestly, I don't know what I'm doing with this cookbook, so I'm going to be trusting @shoekstra to review things that aren't obvious.

The offer to transfer to sous-chefs is still on the table, but we absolutely will not hard fork while someone with a commit bit is still around.

**Comment by mjuszczak** [comment]
I’m happy to pitch in with reviews as well. I haven’t had a chance to work on resolving outstanding issues, but I also have a commit bit, and hope to have more time soon.

**Comment by josephholsten** [comment]
@mjuszczak well I realized that I don't actually have perms to release the cookbook to supermarket, but I think you do. Hopefully @shoekstra and I can knock down some of the backlog to make it worth releasing soon.

**Comment by mjuszczak** [comment]
OK! I will try to pitch in some cycles soon, too.

**Comment by shoekstra** [comment]
Issue has been open over a year and now there is more active development happening.  No reason to keep this open longer.
