### ISSUE TITLE
Ubuntu 16.04. compatibility

### ISSUE THREAD

**Issue by goatherd** [sous-chefs/mariadb#107]
Found two issues when setting this up for Ubuntu 16.04.

The packed client dev package is called `libmariadb-client-lgpl-dev`.
It should be possible to modify the hard-coded `libmariadbclient-dev` through configuration.

Ubuntu 16.04. comes with native mariadb 10.0 packages.
It will install but there are warnings from the cookbook stating the OS does not have the packages.

**Comment by sinfomicien** [comment]
Hi goatherd !

Is it possible for you, to prepare a PR for that ? I'm really out of bandwith to work on your issue for now... And i know it can take months before i found time to work on it !

Thx in advance :)

**Comment by goatherd** [comment]
Hi Nicolas,

only dumping notices for now testing a new deployment. Having those notes often helps me determine issues faster so maybe someone else will profit from it until a fix is demanded/ provided.

As there still are several weird issues with Ubuntu 16.04. and some discussion with the MySQL 5.7 incompatibility it is not to certain that I will rely on the cookbook for now. If the team chooses MariaDB I'll provide a pull request afterwards.

Somewhat short on time as well.

**Comment by PowerKiKi** [comment]
Also trying to converge on Ubuntu 16.04 and unfortunately stucked with a repository key that is apparently missing. Without that key, packages are not installed. But the following command allow to continue:

``` sh
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys  F1656F24C74CD1D8
```

The thing is I don't understand where this key is coming from. I thought the mariadb repository key was CBCB082A1BB943DB ?

@goatherd did you not encounter such error ?

**Comment by goatherd** [comment]
@PowerKiKi the only issue with the keyserver I know of is proxy-related: some old VM installs rejected the keyserver request. Not sure that was a host routing issue or port forwarding related.
Never had any such issues with server deployments nor with MariaDB.

Not being able to update or install from the base repository is rather weird. Are you sure the network is working and unrestricted?

Also unrelated to the issue.

**Comment by damm** [comment]
I didn't really have much of a problem with this cookbook on 16.04 but I ran into the issue with 10.0 being shipped; just made my wrapper call the repository to be added and .. it worked fairly painlessly

**Comment by PowerKiKi** [comment]
Thank you all for your feedback and sorry for hijacking this thread. I'll give another try in the coming weeks and open a separate issue if I can better pinpoint what's going on.

**Comment by damm** [comment]
@PowerKiKi no problem I had to modify the cookbook to handle the different apt key.  We seem to be using a hardcoded key :(

``` diff
diff --git a/cookbooks/mariadb/attributes/apt.rb b/cookbooks/mariadb/attributes/apt.rb
new file mode 100644
index 0000000..2b85044
--- /dev/null
+++ b/cookbooks/mariadb/attributes/apt.rb
@@ -0,0 +1,3 @@
+node.default['mariadb']['apt']['keyserver']="hkp://keyserver.ubuntu.com:80"
+node.default['mariadb']['apt']['key']="F1656F24C74CD1D8"
+
diff --git a/cookbooks/mariadb/recipes/repository.rb b/cookbooks/mariadb/recipes/repository.rb
index e8081eb..25ffe4b 100644
--- a/cookbooks/mariadb/recipes/repository.rb
+++ b/cookbooks/mariadb/recipes/repository.rb
@@ -15,8 +15,8 @@ if node['mariadb']['use_default_repository']
         node['mariadb']['install']['version'] + '/' + node['platform']
       distribution node['lsb']['codename']
       components ['main']
-      keyserver 'hkp://keyserver.ubuntu.com:80'
-      key '0xcbcb082a1bb943db'
+      keyserver node['mariadb']['apt']['keyserver']
+      key node['mariadb']['apt']['key']
     end
   when 'yum'
     include_recipe 'yum::default'
```

**Comment by joraff** [comment]
Doesn't look like the above made it into a PR. May I?

**Comment by damm** [comment]
@joraff if it's not already done feel free.

I believe the key is different for each distribution so ideally if we are to deliver defaults; it would need to have some platform_for_values or some magic to give the right key to find per distro.

**Comment by liamdawson** [comment]
Can confirm that I cannot install on Ubuntu 16.04 without first running this command in the bento vagrant box:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys  F1656F24C74CD1D8
```

Any progress? I'm relying on this cookbook transitively through the boulder server for letsencrypt integration testing.

**Comment by liamdawson** [comment]
I had to mess around with keys to get an installation happening, was having issues with this cookbook as a transitive dependency. I think the winner was this one:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F1656F24C74CD1D8
```
but I haven't confirmed yet.

**Comment by PowerKiKi** [comment]
I never could pinpoint exactly what was going on since last September, but my solution also involved using the key `F1656F24C74CD1D8` for a manual install via `apt_repository` resource. This was the easiest I could come up with without messing too much with this cookbook. In the end that seems to be the same as @liamdawson.

**Comment by damm** [comment]
The key changes based on what distro/version of distro you run.  :( If that helps
