### ISSUE TITLE
Missing quotes in mariadb_grants template

### ISSUE THREAD

**Issue by goatherd** [sous-chefs/mariadb#108]
https://github.com/sinfomicien/mariadb/blob/e842e253a077ee7935b13558da0e0b2a636ca98d/templates/default/mariadb_grants.erb#L24 should quote `$user_exists` to avoid `[execute] /etc/mariadb_grants: line 13: [: ==: unary operator expected` message on run.

Would break following steps within the template but will not do other 'harm'. Only occurs if there is nothing to remove.

**Comment by jwmarshall** [comment]
Ran into the same thing just now. It's really bothersome that this also doesn't stop the chef run.  

The `$user_exists` variable as well as the value on the right side of the comparison should both be double quoted. Further to that, the script should be executed with the `-e` flag such that its exit code is accurate.

**Comment by goatherd** [comment]
PR works for me so this is fixed.
