### ISSUE TITLE
Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by stiller-leser** [sous-chefs/mariadb#113]
Hi,

I'm trying to get this set up using the Vagrantfile. But I get the following:

> ==> galera-cluster-1: [2016-08-18T12:26:46+00:00] INFO: Chef Run complete in 6.949809228 seconds
> ==> galera-cluster-1: [2016-08-18T12:26:46+00:00] INFO: Skipping removal of unused files from the cache
> ==> galera-cluster-1: 
> ==> galera-cluster-1: Running handlers:
> ==> galera-cluster-1: [2016-08-18T12:26:46+00:00] INFO: Running report handlers
> ==> galera-cluster-1: Running handlers complete
> ==> galera-cluster-1: [2016-08-18T12:26:46+00:00] INFO: Report handlers complete
> ==> galera-cluster-1: Chef Client finished, 0/19 resources updated in 9.112061094 seconds
> ==> galera-cluster-1: [2016-08-18T12:26:47+00:00] DEBUG: Forked instance successfully reaped (pid: 8293)
> ==> galera-cluster-1: [2016-08-18T12:26:47+00:00] DEBUG: Exiting
> ==> galera-cluster-1: Running provisioner: shell...
>     galera-cluster-1: Running: inline script
> ==> galera-cluster-1: mesg: 
> ==> galera-cluster-1: ttyname failed
> ==> galera-cluster-1: : 
> ==> galera-cluster-1: Inappropriate ioctl for device
> ==> galera-cluster-1: ERROR
> ==> galera-cluster-1:  1045 (28000)
> ==> galera-cluster-1: : Access denied for user 'root'@'localhost' (using password: NO)

The ioctl-part is the Ubuntu 16.04 screw up (even though I am using the bento image). This is however just a message. It's crashing because of the other error, which I cannot really pin down.

I set the following variables in the default.rb:

> default['mariadb']['server_root_password']              = 'testtest'
> default['mariadb']['galera']['wsrep_sst_method']   = 'xtrabackup-v2'
> default['mariadb']['galera']['wsrep_sst_auth']     = 'root:testtest'
> default['mariadb']['debian']['password'] = 'testtest'

Any hint as to where the error lies is appreciated. I'm confused since Chef runs fine, but crashes at the end.

Thanks!

**Comment by stiller-leser** [comment]
Hey,

late Friday discovery: The issue was the rubocop invocation in the Vagrantfile. If you set a database password during the chef run you first need to configure this in the Vagrantfile like so: `db_config.vm.provision 'shell', inline: "mysql -u root --password=testtest -e`

That took me way to long to discover. I'll leave the issue open in case anyone fancys a pull request.

Enjoy the weekend,
stiller-leser

**Comment by damacus** [comment]
@shoekstra I think this can be fixed when "we" sort out the kitchen testing
