### ISSUE TITLE
Add a secure section

### ISSUE THREAD

**Issue by sinfomicien** [sous-chefs/mariadb#14]
As someone asked me by mail, this cookbook need a 'secure' version which can be applied both on server and galera.

The goal is to simulate the result of the mariadb_secure_installation script, via attributes:

- [ ] set a secure root password (via openssl opscode cookbook)
- [x] remove test database
- [x] remove anonymous login
- [x] remove root remote access (already done, but put the attribute in secure section)

**Comment by martinb3** [comment]
https://github.com/sinfomicien/mariadb/issues/65 would also apply here.

**Comment by chewi** [comment]
I just spent a good half an hour trying to figure out why my `'foo'@'%'` GRANT wasn't working and eventually discovered it was due to the presence of the anonymous login. This is very annoying.
