### ISSUE TITLE
Bug with data directory move + 10.1 + Ubuntu 16

### ISSUE THREAD

**Issue by JCotton1123** [sous-chefs/mariadb#162]
I haven't tracked down this error yet so I'll try to include as much info as possible. To replicate it, set the version to `10.1` and set an alternate data directory like so:

```
diff --git a/.kitchen.yml b/.kitchen.yml
index 49e3fba..be2a8ac 100644
--- a/.kitchen.yml
+++ b/.kitchen.yml
@@ -26,6 +26,10 @@ suites:
     attributes:
       mariadb:
         use_default_repository: true
+        install:
+          version: '10.1'
+        mysqld:
+          datadir: /mysql
```

This will result in the following error:

```
       * execute[install-grants] action run

           ================================================================================
           Error executing action `run` on resource 'execute[install-grants]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Command execution failed. STDOUT/STDERR suppressed for sensitive resource

           Resource Declaration:
           ---------------------
           suppressed sensitive resource output

           Compiled Resource:
           ------------------
           suppressed sensitive resource output

           System Info:
           ------------
           chef_version=13.0.118
           platform=ubuntu
           platform_version=16.04
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
           program_name=chef-client worker: ppid=1601;start=05:36:21;
           executable=/opt/chef/bin/chef-client

         * service[mysql] action enable (up to date)
```

This is failing b/c the mysql database somehow doesn't exist:

```
root@default-ubuntu-1604:~# mysql -e 'show databases'
+--------------------+
| Database           |
+--------------------+
| information_schema |
+--------------------+
```

This seems to be a "recent" issue b/c the same issue does not occur with the 0.3.x branch which is why I opened https://github.com/sinfomicien/mariadb/pull/161.

**Comment by shoekstra** [comment]
@JCotton1123, to confirm the issue:

With the master branch/current release:

* Using data dir move with Ubuntu 16 and MariaDB 10.0 _does work_
* Using data dir move with Ubuntu 16 and MariaDB 10.1 _does not work_

With the 0.3.x branch:

* Using data dir move with Ubuntu 16 and MariaDB 10.0 _does work_
* Using data dir move with Ubuntu 16 and MariaDB 10.1 _does work_

Is the above correct?

Are you trying to move the data dir during initial bootstrap or moving the data dir of a running server?

**Comment by JCotton1123** [comment]
Yes, I believe the above is correct however I was testing various permutations of Chef client, MariaDB version, and Ubuntu version when I was trying to track this down so it probably wouldn't hurt to re-verify the above. I'll try to do that when I have some time.

The data dir move is only during the initial bootstrap.

**Comment by JCotton1123** [comment]
Confirming this issue appears to be specific to Ubuntu 16 and MariaDB 10.1. The issue appears to be that Chef fails to shutdown the mysql service before performing the datadir move. Chef reports `* service[mysql] action stop (up to date)` however the service is running. If I run `service mysql stop` or `systemctl stop mysql` the service does successfully stop. Guessing the issue might be related to systemd given that it only impacts Ubuntu 16. I did try manually setting the service provider to `systemd` but that had no impact.

**Comment by shoekstra** [comment]
Thanks for the investigations thus far! Interesting that it works in an older cookbook version...

Hopefully I should have some time next week to dive into this one as some colleagues are also looking for 10.1 support. We predominantly use CentOS but would be good to make it work across all platforms and do a major version bump of this cookbook.
