### ISSUE TITLE
undefined method

### ISSUE THREAD

**Issue by DMEvanCT** [sous-chefs/mariadb#169]
10.1.0.44
10.1.0.44 ================================================================================
10.1.0.44 Recipe Compile Error in /var/chef/cache/cookbooks/mariadb/recipes/_redhat_server.rb
10.1.0.44 ================================================================================
10.1.0.44
10.1.0.44 NoMethodError
10.1.0.44 -------------
10.1.0.44 undefined method `use_os_native_package?' for cookbook: mariadb, recipe: _redhat_server :Chef::Recipe
10.1.0.44
10.1.0.44 Cookbook Trace:
10.1.0.44 ---------------
10.1.0.44   /var/chef/cache/cookbooks/mariadb/recipes/_redhat_server.rb:20:in `from_file'
10.1.0.44
10.1.0.44 Relevant File Content:
10.1.0.44 ----------------------
10.1.0.44 /var/chef/cache/cookbooks/mariadb/recipes/_redhat_server.rb:
10.1.0.44
10.1.0.44  13:  # Unless required by applicable law or agreed to in writing, software
10.1.0.44  14:  # distributed under the License is distributed on an "AS IS" BASIS,
10.1.0.44  15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
10.1.0.44  16:  # See the License for the specific language governing permissions and
10.1.0.44  17:  # limitations under the License.
10.1.0.44  18:  #
10.1.0.44  19:
10.1.0.44  20>> use_os_native = use_os_native_package?(node['mariadb']['install']['prefer_os_package'],
10.1.0.44  21:                                         node['platform'],
10.1.0.44  22:                                         node['platform_version'])
10.1.0.44  23:  use_scl = use_scl_package?(node['mariadb']['install']['prefer_scl_package'],
10.1.0.44  24:                             node['platform'],
10.1.0.44  25:                             node['platform_version']) &&
10.1.0.44  26:            scl_version_available?(node['mariadb']['install']['version'])
10.1.0.44  27:
10.1.0.44  28:  # To force removing of mariadb-libs on CentOS >= 7
10.1.0.44  29:  package 'MariaDB-shared' do
10.1.0.44
10.1.0.44 System Info:
10.1.0.44 ------------
10.1.0.44 chef_version=13.3.42
10.1.0.44 platform=centos
10.1.0.44 platform_version=7.3.1611
10.1.0.44 ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
10.1.0.44 program_name=chef-client worker: ppid=2206;start=12:26:46;
10.1.0.44 executable=/opt/chef/bin/chef-client
10.1.0.44
10.1.0.44
10.1.0.44 Running handlers:
10.1.0.44 [2017-08-29T12:26:54-04:00] ERROR: Running exception handlers
10.1.0.44 Running handlers complete
10.1.0.44 [2017-08-29T12:26:54-04:00] ERROR: Exception handlers complete
10.1.0.44 Chef Client failed. 0 resources updated in 08 seconds
10.1.0.44 [2017-08-29T12:26:54-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
10.1.0.44 [2017-08-29T12:26:54-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
10.1.0.44 [2017-08-29T12:26:54-04:00] ERROR: undefined method `use_os_native_package?' for cookbook: mariadb, recipe: _redhat_server :Chef::Recipe
10.1.0.44 [2017-08-29T12:26:54-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
PS C:\Users\ehaston\ChefMad\cookbooks>

**Comment by shoekstra** [comment]
Hi!

Sorry for the delayed response - can you test if this is fixed in the latest version (1.5.2)?

There has been some refactoring and the tests seem to pass.  If you still have a problem please let me know how I can replicate.

Cheers,
Stephen

**Comment by xorima** [comment]
Hi, 
Closing issue as we have released 2.0.0 which does not use recipes anymore, if you are still having an issue please re-open 

Thanks
