### ISSUE TITLE
Changing version DOES NOT install it

### ISSUE THREAD

**Issue by ragingdave** [sous-chefs/mariadb#179]
During initial configuration/testing of this package, I found that if you change the version the actual package doesn't get updated. Is this intended as it caused mariadb to fail to start completely with incompatible settings for the targeted version?

**Comment by sinfomicien** [comment]
At the beginning, i did it that way. The biggest problem is the incompatibility with version, as you guess it. Perhaps, It could be a good idea to allow it only for minor version upgrade...
And when i tried, the downgrade failed 90% of the time.

So as i haven't so many time to do differently... If your wanna push a PR, feel free 😉
