### ISSUE TITLE
lc_messages_dir is different on CentOS

### ISSUE THREAD

**Issue by sbcas** [sous-chefs/mariadb#181]
`mariadb-server` from CentOS 7 base appears to have a different location for `lc_messages_dir` than `/usr/share/mysql`:

```
Oct 20 21:39:16 default-centos-73.vagrantup.com mysqld[17615]: 2017-10-20 21:39:16 140468908144832 [Note] /usr/libexec/mysqld (mysqld 10.1.20-MariaDB) starting as process 17615
Oct 20 21:39:16 default-centos-73.vagrantup.com mysqld[17615]: 2017-10-20 21:39:16 140468908144832 [ERROR] Can't find messagefile '/usr/share/mysql/errmsg.sys'
Oct 20 21:39:16 default-centos-73.vagrantup.com mysqld[17615]: 2017-10-20 21:39:16 140468908144832 [ERROR] Aborting
Oct 20 21:39:16 default-centos-73.vagrantup.com systemd[1]: mariadb.service: main process exited, code=exited, status=1/FAILURE
Oct 20 21:39:16 default-centos-73.vagrantup.com systemd[1]: Failed to start MariaDB 10.1 database server.
```

This is also the case with CentOS 7.4. `mariadb` does start when `lc_messages_dir` is set to `/usr/share/mariadb`

**Comment by dimsh99** [comment]
I can't replicate it.
Package doesn't bring /usr/share/mysql/errmsg.sys. There is errmsg.sys for each language though ( i.e. /usr/share/mysql/english/errmsg.sys) and mariadb seems to find correct file. Maybe this happens due to some problems with locale or language settings?

**Comment by sbcas** [comment]
Never mind. I'll leave my workaround in place.

**Comment by shoekstra** [comment]
@scassiba if you could provide a kitchen config that replicates how you use the cookbook so we can reproduce it that would be great.  I came across [this post](https://askubuntu.com/questions/102875/mysql-5-5-starts-and-then-instantly-stops) that seems to describe your issue and the fix, not sure if it's similar, but unfortunately I too can't reproduce it.  I also run MariaDB on CentOS and we have a couple of integration tests for CentOS that are passing, both running as mysql server and a galera instance.

Please reopen if you're able to provide more info so we can take a look.

Cheers, Stephen
