### ISSUE TITLE
xtrabackup-v24 missing from centOS 7 repos

### ISSUE THREAD

**Issue by ragingdave** [sous-chefs/mariadb#183]
Currently using xtrabackup-v2 with mariaDB 10.2 is incompatible and creates a issue where checkpoints aren't recognized and causes SST to faile in a Galera cluster configuration. Since this package already handles installing the (currently unavailable) xtrabackup-v24, shouldn't it also configure the repo for percona xtrabackup24?

**Comment by sinfomicien** [comment]
I think that the real solution would be to install the new mariabackup instead. Will do it and try it
