### ISSUE TITLE
Data Bags in Galera config not working

### ISSUE THREAD

**Issue by ragingdave** [sous-chefs/mariadb#184]
Upon trying to use data bags in the galera configuration of passwords and sst user config, I find that those don't work at all and when configured as I would expect them to be configured.....doesn't apply the desired settings and further, produces an error which prevents chef from running.

roles/galera.json
```
{
  ...
  "mariadb": {
    ...
    "galera": {
      ...
      "wsrep_sst_auth": ""
      ...
    }
    ...
  }
  ...
}
```
data_bags/mariadb/user_sstuser.json:
```
{
  "id": "user_sstuser",
  "user_password": "user:password"
}
```
Is this not the correct layout/configuration?

If I don't set the wsrep_sst_auth to an empty string then the default sstuser creds defined in the default attributes get applied.

**Comment by sinfomicien** [comment]
The version 2.0 and more of this cookbook does not manage any databag. You could use it when writing your recipe, and using custom resources.

So i closed this issue.
