### ISSUE TITLE
Add resources to manage databases and users

### ISSUE THREAD

**Issue by stissot** [sous-chefs/mariadb#185]
I was using the `mysql_database` and `mysql_user` resources provided by the [`database`](https://supermarket.chef.io/cookbooks/database) cookbook, but this cookbook is now deprecated.

The [reason why it's deprecated](https://github.com/chef-boneyard/database#deprecation) is because the authors think these resources should be implemented by each specialized database cookbook, to better use the full feature set of the underlying DB system.

So I think the `mariadb` cookbook should provide similar `mariadb_database` and `mariadb_user` resources/providers.

See also similar topic on the mysql cookbok: https://github.com/chef-cookbooks/mysql/issues/522

**Comment by PowerKiKi** [comment]
There is also a similar topic, and conclusion, on https://github.com/sous-chefs/postgresql/issues/437

Forking some `database` features into this repository sounds like a good idea. If the core team agree on that, then @stissot or myself, could work on a PR for that. Would that be OK ?

**Comment by josephholsten** [comment]
@stissot if you find those resources valuable, then please go for it! Do you need anything besides approval from the rest of us?

**Comment by stissot** [comment]
@josephholsten I've made a PR #187 can you please review it?

**Comment by jmadureira** [comment]
@stissot I've been trying out the `mariadb_user` resource and it fails on the second run. It appears that the `load_current_value` on the resource is not telling chef that the resource already exists so it tries to create a new one.

Also the PR #187 doesn't include any matchers for the new resources. I don't know if it is expected or not.

**Comment by infertux** [comment]
> mariadb_user resource and it fails on the second run

@jmadureira I could not reproduce this issue. Is it happening with `action :create`? Here's what I tried:

```diff
diff --git i/test/fixtures/cookbooks/mariadb_test/recipes/resources.rb w/test/fixtures/cookbooks/mariadb_test/recipes/resources.rb
index ddc79b6..545b488 100644
--- i/test/fixtures/cookbooks/mariadb_test/recipes/resources.rb
+++ w/test/fixtures/cookbooks/mariadb_test/recipes/resources.rb
@@ -75,6 +75,12 @@ mariadb_user 'piggy' do
   action :create
 end
 
+# create user piggy again
+mariadb_user 'piggy2' do
+  username 'piggy'
+  action :create
+end
+
```

```bash
$ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen converge resources-debian-8
[...]
  * mariadb_database[datatrout] action drop (up to date)
  * mariadb_user[piggy] action create (up to date)
  * mariadb_user[piggy2] action create (up to date)
  * mariadb_user[kermit] action drop (up to date)
[...]
```

I converged multiple times and Chef is properly detecting that the resource is up to date for me.

**Comment by jmadureira** [comment]
@infertux I was able to find out where the problem is and created the #191 with a possible fix.

**Comment by stissot** [comment]
@jmadureira see my answers on #191
