### ISSUE TITLE
No candidate version available for libmariadbclient-dev

### ISSUE THREAD

**Issue by onknows** [sous-chefs/mariadb#186]
On Ubuntu 16.04 mariadb::client will not work. It shows error
No candidate version available for libmariadbclient-dev

Cookbook version is 1.5.3

The package is renamed maybe? It is called libmariadb-client-lgpl-dev now? I'm not sure.

**Comment by shoekstra** [comment]
Hi!

I hope to spend some time on this cookbook in the next few days and will see if I can get this one fixed then.

Stephen
