### ISSUE TITLE
Create new release so new resources are available

### ISSUE THREAD

**Issue by petracvv** [sous-chefs/mariadb#199]
I am trying to use this cookbook but the version on the supermarket does not include the ported over resources from the database cookbook (pull #187) and I would rather not depend on that deprecated cookbook if possible.

Could we have a new release made and published to chef supermarket?

**Comment by sinfomicien** [comment]
You're right... Will try to find time to publish it this week. Or next one at max. I would like to see some new PR merged before, some need a little work.
