### ISSUE TITLE
Correct FC113 warning with Foodcritic

### ISSUE THREAD

**Issue by sinfomicien** [sous-chefs/mariadb#200]
Hello dear community,

  Chef 12 has now reached end of life... So Foodcritic has deprecated the call to use_inline_resource. Do we need to correct it (by removing the call to this now default function)? or ask foodcritic to ignore this warning ?

  I don't have a clear opinion on that.. Different point of view welcomed. Thanks !!!

**Comment by sinfomicien** [comment]
I answer to myself. As we want to keep a chef 12 compatibility, we have to ignore that warning. We'll have to remove the ignore tag when we will remove chef12 compatibility.

**Comment by josephholsten** [comment]
Can we document why we’re supporting chef 12, and under what circumstances we will to stop supporting it?

**Comment by sinfomicien** [comment]
That's a very good question... I figure that everywhere in tests, we force chef12 version. Probably because a lot of us, use it.  But it was set by @shoekstra, perhaps he can say us why chef 12 support ?

To my opinion, as chef 12 has reached end of life, it seems a good idea to remove it, in favor of chef 13. But i don't want to break everything without having other point of view.

**Comment by sinfomicien** [comment]
At least for the next 1.5.4 version, i won't change that support. I will propose a new issue to remove it with version 1.6.0
