### ISSUE TITLE
Cookbook error with attribute default['mariadb']['use_default_repository'] = flase

### ISSUE THREAD

**Issue by GaneshKudikala** [sous-chefs/mariadb#218]
### Cookbook version
lastest version **v1.5.4.zip**

### Chef-client version
**Chef Development Kit Version: 3.1.0**
chef-client version: 14.2.0
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.4
kitchen version: 1.22.0
inspec version: 2.1.72

### Platform Details
**Local Ubuntu 18**
### Scenario:

Not able to run cookbook from the release when i try to run.

### Steps to Reproduce:
 changed line in attributes from  default['mariadb']['use_default_repository'] = flase 

to **default['mariadb']['use_default_repository'] = true it is working fine**

### Expected Result:
Install maria db but not worki
### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by xorima** [comment]
Hi, 
Closing issue as we have released 2.0.0 which does not use recipes any more, if you are still having an issue please re-open 

Thanks
