### ISSUE TITLE
Issue trying to install with Ubuntu 12.04 VM

### ISSUE THREAD

**Issue by rgunijan** [sous-chefs/mariadb#23]
I am trying to install mariadb server with chef, vagrant. I am getting following error while trying to install with chef.add_recipe "mariadb::server

ERROR: package[mariadb-server-10.0](mariadb::_debian_server line 53) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for mariadb-server-10.0

**Comment by sinfomicien** [comment]
Have you try to set the attribute `node['mariadb']['use_default_repository']` to true ?

**Comment by rgunijan** [comment]
Thanks! It worked.
