### ISSUE TITLE
Grant action should not require and modify the password

### ISSUE THREAD

**Issue by sekrett** [sous-chefs/mariadb#236]
### Cookbook version
1.5.4

### Chef-client version
14.10.9

### Platform Details
CentOS 7

### Scenario:
In general when I create a mysql user, I need the password, but when I grant permissions, it does not need the password, it is a different action. Also from documentation it is not clear if I can do a grant with password assuming the user will be created as well. If grant action modifies the password, why should I specify the password in create action? Why should I specify the password twice according to documentation?

### Steps to Reproduce:
```ruby
mariadb_user 'user' do
  database_name 'db'
  action :grant
end
```

### Expected Result:
It should only grant permissions. If password is supplied or not for `grant` or `revoke` action, ignore it, don't modify it. This should be simple, I can do a PR.

The best solution in my opinion is to split user creation and grant to two different resources, it will make the code cleaner also, but will break everything. Opinions?

### Actual Result:
My password is reset to empty.

**Comment by damacus** [comment]
This sounds like a great first pr.

I think, we want to rewrite to custom resources first, to tidy things up a lot and get it into a well testable state. 

I've opened a draft PR to start things off.

**Comment by sinfomicien** [comment]
It make sense. Will try to write something about it. But unfortunately, will not try to work on the old 1.5.x branch. It will be on 2.x or even 3.x branch.
