### ISSUE TITLE
Mariabackup won't install when using version 10.3, Ubuntu Bionic and mariadb_galera_configuration resource

### ISSUE THREAD

**Issue by cdelacruzpinto** [sous-chefs/mariadb#241]
### Cookbook version
2.0.0

### Chef-client version

14.5.33

### Platform Details
Ubuntu 18.04

### Scenario:
Install a 3 node MariaDB 10.3 cluster using mariabackup method for sst

### Steps to Reproduce:

- Create a wrapper cookbook that uses the mariadb_galera_configuration resource specifying version 10.3 and mariabackup sst option
- Run the cookbook in a Bionic VM/host (I used a three node kitchen configuration file)

### Expected Result:
The cookbook works as a charm and sets up a MariaDB/Galera cluster.

### Actual Result:
The recipe tries to install mariadb-backup-10.3, which is a non-existant package in Bionic, and fails.
 (mariadb-backup package exists in the MariaDB repository, and installs version 10.3)

**Comment by sinfomicien** [comment]
I can reproduce it for all deb package distribution (not only for Ubuntu). Will try to understand why they change naming convention for 10.3 (and if this will be the default for all new versions)

Will soon submit a PR to correct the name for 10.3 version.

**Comment by sinfomicien** [comment]
@cdelacruzpinto, i just merged a patch. Could you please test your use case with the master branch please ? I will release a new version soon.

**Comment by cdelacruzpinto** [comment]
Sure. Will test and let you know. Many thanks!

**Comment by cdelacruzpinto** [comment]
Tested with same previous wrapper cookbook and works for me. Many thanks!
