### ISSUE TITLE
Remove Debian 8 support, add debian 10 support

### ISSUE THREAD

**Issue by sinfomicien** [sous-chefs/mariadb#248]
### Cookbook version
2.1.0

### Chef-client version
14.11.21

### Platform Details
Debian 8 (Jessie)

### Scenario:
Kitchen test are failing for the debian-8 OS

### Steps to Reproduce:
Just launch test on any suite, only on debian 8 

### Expected Result:
The tests passed all without errors

### Actual Result:
An error during convergence:
```
Err http://httpredir.debian.org jessie-updates/main Sources
    404  Not Found [IP: 151.101.120.204 80]
Err http://httpredir.debian.org jessie-updates/main amd64 Packages
    404  Not Found [IP: 151.101.120.204 80]
```

### Proposed solution

As the jessie distribution is old-stable for more than a year... The jessie-updates does not exist anymore. Jessie is only on LTS support (https://wiki.debian.org/LTS/) since june 2018.
So , i propose to completely remove support for debian 8, and introduce early support for debian 10.

What do you think ?

**Comment by damacus** [comment]
Sounds good, if there are dokken images for it

**Comment by sinfomicien** [comment]
It seems someone submit a PR to dokken-images repository to add it (https://github.com/someara/dokken-images/issues/26) 👼

**Comment by damacus** [comment]
Awesome sauce. Next we should go fix https://github.com/sous-chefs/orbs If you need any guidance give me a shout and I'll help :) 

We will probably do a major version change as we're dropping support for Debian 8
