### ISSUE TITLE
Root password is empty when set manually in mariadb_server_install

### ISSUE THREAD

**Issue by anewb** [sous-chefs/mariadb#256]
### Cookbook version
2.1.0

### Chef-client version
14.12.3

### Platform Details
Ubuntu 18.04.1 LTS

### Scenario:
Set root password manually.

### Steps to Reproduce:
Use this resource specification:
```
mariadb_server_install "Install MariaDB Server #{version}" do
	password admin_password
	setup_repo true
	version version
end
```

### Expected Result:
Root password should be set.

### Actual Result:
Root password is empty, anyone can connect via `mysql -u root`.

Tried to work around this by adding
```
mariadb_user 'root' do
	action :create
	password admin_password
end
```

but that only worked on the first run. On subsequent runs this throws a RuntimeError: SQL ERROR, because the root password was set and mariadb_user could not connect without ctrl_password specified. But when ctrl_password is specified, the first run does throw the RuntimeError: SQL ERROR, because the root password is still empty and mariadb_user tries to connect with the password.
Trying to rescue the RuntimeError did not work (i do not understand why, i had this code inside a custom resource action and there rescue should work as far as i know):
```
action :install do
	admin_password = new_resource.admin_password
	version = new_resource.version
	
	mariadb_server_install "Install MariaDB Server #{version}" do
		password admin_password
		setup_repo true
		version version
	end
	
	begin
		mariadb_user 'root' do
			action :create
			password admin_password
		end
	rescue RuntimeError
		mariadb_user 'root' do
			action :create
			ctrl_password admin_password
			password admin_password
		end
	end
end
```

**Comment by nexusVI** [comment]
Same problem on Debian 10. 

I am trying to set the root password from a node attribute, but it always remains empty.

Edit: 
I verified manually that setting the new password like this does not seem to work:
`SET PASSWORD FOR 'root'@'localhost' = PASSWORD('new_password');`

This does work: 
`ALTER USER 'root'@'localhost' IDENTIFIED BY 'new_password';`

**Comment by damacus** [comment]
This sounds like a bug with the provider/resource on setting the password. Does someone fancy looking into fixing this bug, or making a test case in chef spec/inspec to start the process off?

**Comment by jmadureira** [comment]
I've also hit this problem and after some debugging I noticed an error while trying to change the root password:

```
ERROR: 1356  View 'mysql.user' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
```

So the problem is related to this query on the `/var/lib/mysql/recovery.conf` file.

```
update user set password=PASSWORD('########') where User='root';
```

Changing this to something like

```
ALTER USER 'root'@'localhost' IDENTIFIED BY '########';
```

does fixes the problem on my end but I'm not entirely certain that this is the correct way to fix this.

**Comment by stissot** [comment]
Since MariaDB 10.4, at least on Debian/Ubuntu, the default `root` account has only the `unix_socket` authentication plugin activated (he can only login from the `root` Unix user, without a password), not the `mysql_native_password`. That's why we cannot set the root password until we enable the password plugin. Here is the fix for `recovery.conf`:

```
ALTER USER root@localhost IDENTIFIED VIA unix_socket OR mysql_native_password USING PASSWORD('######');
FLUSH PRIVILEGES;
```
