### ISSUE TITLE
Centos 6/7 tests failing to find packages

### ISSUE THREAD

**Issue by JohnRoesler** [sous-chefs/mariadb#276]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

The galera-configuration-centos-6/7 tests are failing.
- [centos-6](https://circleci.com/gh/sous-chefs/mariadb/2438)
  - `No candidate version available for socat, pv, mariadb-backup`
- [centos-7](https://circleci.com/gh/sous-chefs/mariadb/2453)
  - ` No candidate version available for pv, mariadb-backup`

## :pancakes: Cookbook version

2.1 current. Releasing 3.0

## :woman_cook:  Chef-Infra Version

latest

## :tophat: Platform details

centos 6/7

## Steps To Reproduce

`kitchen test galera-configuration-centos-6`
`kitchen test galera-configuration-centos-7`

## :police_car: Expected behavior

Test passes

## :heavy_plus_sign: Additional context

none

**Comment by ccrebolder** [comment]
for `pv` and `socat` I had to add the epel repo to the test cookbook recipe. I assume we would not want to manage this for users, but let me know if there's a better way.

for `MariaDB-backup` the yum package has capital letters in it, like the server package
