### ISSUE TITLE
Undefined method trying to run mariadb_configuration

### ISSUE THREAD

**Issue by dguertin** [sous-chefs/mariadb#367]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

When including mariadb_configuration in a recipe, chef-client runs fail with:

> FATAL: NoMethodError: undefined method `[]' for nil:NilClass

## :pancakes: Cookbook version

4.1.3

## :woman_cook:  Chef-Infra Version

The problem occurs with both 17.10.3 and 18.2.7.

## :tophat: Platform details

Alma Linux 8.7

## Steps To Reproduce

1. Include mariadb_configuration in a recipe. Any configuration I've tried gives the same result, but one example is 
```
mariadb_configuration 'innodb' do
  section 'mysqld'
  option innodb_thread_concurrency: 8,
         innodb_commit_concurrency: 8,
         innodb_read_io_threads: 8,
         innodb_flush_log_at_trx_commit: 1
end
```
2. Run chef-client.
3. Error:
```Running handlers:
[2023-04-25T14:35:48-04:00] ERROR: Running exception handlers
Running handlers complete
[2023-04-25T14:35:48-04:00] ERROR: Exception handlers complete
Infra Phase failed. 23 resources updated in 01 minutes 28 seconds
[2023-04-25T14:35:48-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2023-04-25T14:35:48-04:00] FATAL: ---------------------------------------------------------------------------------------
[2023-04-25T14:35:48-04:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
[2023-04-25T14:35:48-04:00] FATAL: ---------------------------------------------------------------------------------------
[2023-04-25T14:35:48-04:00] FATAL: NoMethodError: mariadb_configuration[innodb] (mariadb-midd::config_alma8 line 25) had an error: NoMethodError: undefined method `[]' for nil:NilClass
```

## :police_car: Expected behavior

Chef-client completes and writes a config file to /etc/my.cnf.d/innodb.cnf.

## :heavy_plus_sign: Additional context

I'm not actually sure if this is a bug, or if I've just got something set up wrong, but if I've got something wrong I haven't been able to find it.

Stacktrace:
[chef-stacktrace.out.gz](https://github.com/sous-chefs/mariadb/files/11325807/chef-stacktrace.out.gz)

**Comment by fernandoaleman** [comment]
@dguertin Did you do a server install with the `mariadb_server_install` resource before the `mariadb_configuration`? I am thinking that might be why you are getting that error.

**Comment by dguertin** [comment]
Thank you! That was indeed the solution. I don't understand why this would be needed, though, if I've already installed MariaDB in another recipe with the `package` resource. What is `mariadb_server_install` doing that allows `mariadb_configuration` to succeed, or put another way, what is `package` not doing?

**Comment by fernandoaleman** [comment]
> What is `mariadb_server_install` doing that allows `mariadb_configuration` to succeed, or put another way, what is `package` not doing?

It's failing because the mariadb [ext_conf_dir](https://github.com/sous-chefs/mariadb/blob/main/libraries/helpers.rb#L176) helper cannot find the `node.run_state['mariadb']['version']` which is set [here](https://github.com/sous-chefs/mariadb/blob/main/resources/server_install.rb#L30) in the mariadb_server_install resource.
