### ISSUE TITLE
The root password is not set

### ISSUE THREAD

**Issue by stissot** [sous-chefs/mariadb#4]
While the attribute `node['mariadb']['server_root_password']`, the server or config recipes do not set it, the root password is empty after install.

**Comment by sinfomicien** [comment]
I agree... I updated the documentation, but the associated code is on a branch which i snot fully tested. I will publish it as soon as possible.

**Comment by sinfomicien** [comment]
Hi Sylvain,

Could you verify that my implementation meets your needs ? If it's ok, i will release the 0.2.3 on the supermarket.

**Comment by stissot** [comment]
Thanks Nicolas, the implementation to set the password is working great, tested on Ubuntu 14.04 and MariaDB 5.5
