### ISSUE TITLE
resources that deal with passwords need the sensitive flag

### ISSUE THREAD

**Issue by kramvan1** [sous-chefs/mariadb#40]
For example, there are several places calling the command line and passing the root password in the clear:

https://github.com/sinfomicien/mariadb/blob/935522ed6e6bae0749b0ecb5a5d713bbf08a02d3/providers/replication.rb#L56
and line 70, 84, 98.

https://github.com/sinfomicien/mariadb/blob/935522ed6e6bae0749b0ecb5a5d713bbf08a02d3/recipes/_redhat_galera.rb#L39

https://github.com/sinfomicien/mariadb/blob/935522ed6e6bae0749b0ecb5a5d713bbf08a02d3/recipes/_redhat_server.rb#L35

https://github.com/sinfomicien/mariadb/blob/e7412244dcce3b276fd6a1b7ccf68a8d691e2d2e/recipes/galera.rb#L119
and line 124.

This is dependent upon: https://github.com/opscode/chef/pull/2013 which is in Chef 11.14

Looks like foodcritic still does not have full support for this: https://github.com/acrmp/foodcritic/issues/233
will have to backout the execute changes for now

**Comment by kramvan1** [comment]
Pull request 41  
https://github.com/sinfomicien/mariadb/pull/41

**Comment by sinfomicien** [comment]
I will review your code tonight, but i just discovered this option. Thx for your PR!

**Comment by sinfomicien** [comment]
I close the issue, as the PR is merged.
