### ISSUE TITLE
Add support for Centos7

### ISSUE THREAD

**Issue by rferguson10** [sous-chefs/mariadb#56]
In client.rb it is setting the client package name to be MariaDB-client when under the 'rhel' section. Although using yum itself, i can see that to install the maridb client it is simply "maria".

Right now I'm getting an error Error executing action `install` on resource 'yum_package[MariaDB-client]'

**Comment by sinfomicien** [comment]
Hi, i'm reviewing the PR #55 ... I think it will correct your problem. If everything good in i will merge it soon.

**Comment by kramvan1** [comment]
Looks like #55 fixed the issue.  When will be see latest version tagged and released out on the supermarket?

**Comment by kramvan1** [comment]
@sinfomicien  Just wondering again, would like to see 0.3 tagged into supermarket, anytime soon?

**Comment by jjasghar** [comment]
We have a downstream cookbook and [dependency](https://blueprints.launchpad.net/openstack-chef/+spec/mariadb-support) for OpenStack needing this pushed and tagged to 0.3.0, can you help us out?
![selfie-0](http://i.imgur.com/pKrcAAA.png)

**Comment by sinfomicien** [comment]
Hi all, sorry for the delay... @mfouilleul did the job to publish the latest version to supermarket (thx to him)

Thx @yinym for the PR, and my apologies for being late to release :)

**Comment by jjasghar** [comment]
Thanks!
