### ISSUE TITLE
Provide configuration to create Galera cluster using Vagrant

### ISSUE THREAD

**Issue by bendodd** [sous-chefs/mariadb#60]
It seems useful to have an multi-node Galera cluster running locally in a multi-node Vagrant environment. To do this I would like to devise and commit back:
1. A pull request to allow Chef Solo to be used (currently by defining the cluster IPs manually as opposed to using the search functionality of Chef Server/Zero e.g. https://github.com/armakuni/mariadb/commit/0f13f6eb1ae37203047b03c4e0aa3c181e3c7299 )
2. Vagrant configuration for a multi-node Vagrant e.g. https://gist.github.com/bendodd/f599fa25da9d5cd80162

Advice need:
1. Which recipe(s) needs to be run to create a cluster?
2. Confirm the recipes are idempotent
3. Confirm additional nodes can be added
4. Approach to node failure
5. Approach to node load balancing - e.g. HAProxy implementation

^^^ This would be good documentation, for at least me

**Comment by sinfomicien** [comment]
Here you will find more documentation on Galera Specific case:

https://github.com/sinfomicien/mariadb/blob/master/galera.md

Will merge the info from the README about Galera into it soon. Does it sound good to help you ?

**Comment by sinfomicien** [comment]
The PR #64 close this ticket.
