### ISSUE TITLE
Do not save passwords to the node object

### ISSUE THREAD

**Issue by martinb3** [sous-chefs/mariadb#65]
Using an attribute for the root password encourages users of this cookbook to set their own root passwords at a higher precedence level, so they can be sure their attribute value is merged over the default attribute value.

```
default['mariadb']['server_root_password']              = ''
```

This means when they do a `normal` or `node.set` of the same attribute, it ends up being saved back to the chef server in plain text. This cookbook should support reading a password from a data bag, encrypted data bag, or `node.run_state` instead.

**Comment by malibuworkcrew** [comment]
+1, putting passwords in data bags is required in many companies

**Comment by shoekstra** [comment]
After much thought I'm going to close this as `won't fix`.

The attribute is like that so you may choose to populate it however you like, whether it be plain text, data bag, encrypted data bag, chef-vault, hashicorp-vault, etc.  As you can see there is a number of options (and perhaps more in the future?) to load the attribute and it would add extra overhead to maintain all possible ways of doing so using this cookbook.

When the onus is on you to populate the value it is also your responsibility to delete the attribute. You can clean up the attribute following the example [found here](http://jtimberman.housepub.org/blog/2014/12/24/quicktip-delete-attributes/) by creating a wrapper cookbook that resembles the following:

```
node.default['mariadb']['server_root_password'] = 'passw0rd'

include_recipe 'mariadb::<recipe>'

ruby_block 'delete-mariadb-attributes' do
  block { node.rm('mariadb', 'server_root_password') }
end
```

Internally at work we have a library that loads attributes and removes them at the end of a Chef run but it's not open source.  If it is made public I will update the README to include it.
