### ISSUE TITLE
mariadb_configuration template uses current cookbook as template source; documentation issue

### ISSUE THREAD

**Issue by mstyne** [sous-chefs/mariadb#66]
When defining a `mariadb_configuration` resource, the template resource in `configuration.rb` references `new_resource.cookbook`, which uses the name of the calling cookbook, which typically(?) isn't `maraidb`, and by default, doesn't have the templates in use defined.

```
================================================================================
Error executing action `create` on resource 'template[/etc/mysql/conf.d/some_conf.cnf]'
================================================================================

Chef::Exceptions::FileNotFound
------------------------------
Cookbook 'some-cookbook' (2.0.0) does not contain a file at any of these locations:
        templates/debian-7.8/conf.d.generic.erb
        templates/debian/conf.d.generic.erb
        templates/default/conf.d.generic.erb
        templates/conf.d.generic.erb
```

Changing the value to:

```
cookbook 'mariadb'
```

resolves this issue. Additionally, the documentation referencing the `option` hash as:

```
  option {foo: 'bar'}
```

fails with a syntax error, while something like

```
option :foo => bar,
  :baz => quux,
```

works. If these are both considered legitimate bugs, I'd be happy to put together a pull request to resolve them.

**Comment by sinfomicien** [comment]
Please submit a PR, seems you're right :)

**Comment by sinfomicien** [comment]
I just corrected the mariadb_configuration problem. I let you submit a PR concerning the documentation :)

**Comment by mstyne** [comment]
@sinfomicien Sure, I can put together a pull request for the documentation. Thanks :)

**Comment by sinfomicien** [comment]
As the PR is merged, i close the issue. Thx for your help!
