### ISSUE TITLE
CentOS 7 service naming inconsistency

### ISSUE THREAD

**Issue by sbcas** [sous-chefs/mariadb#67]
The CentOS 7 package for MariaDB installs mariadb.service at /usr/lib/systemd/system/mariadb.service which causes breakage as the cookbook expects the 'mysql' service to exist.

As a stopgap, the default can be overridden, but the cookbook should expect 'mariadb' instead of 'mysql' for CentOS 7 (and any other flavors that follow the same convention).

**Comment by sinfomicien** [comment]
Hope it's fixed with your PR.
