### ISSUE TITLE
add sensitive option to galera cookbook resources

### ISSUE THREAD

**Issue by BarthV** [sous-chefs/mariadb#70]
https://github.com/sinfomicien/mariadb/blob/v0.3.0/recipes/galera.rb#L120

This FC issue is now closed and merged : https://github.com/acrmp/foodcritic/issues/233 

please add sensitive where it needs to be :)

Thanks for this cookbook !

**Comment by Rockstar04** [comment]
I just put in a PR for this, I also added sensitive to the preseed template resource since it has root passwords as well, can you take a look a the PR and see if there are other resources that should have the sensitive flag set on?

**Comment by sinfomicien** [comment]
Seems the foodcritic i use in Travis is not supporting the feature. If the latest Gem is OK, could you (@Rockstar04) update the Gemfile to the good version (So foodcritic will not warm in Travis).

**Comment by shoekstra** [comment]
Fixed, `sensitive` property has been added where appropriate.
