### ISSUE TITLE
Server and Galera Feature Parity

### ISSUE THREAD

**Issue by Rockstar04** [sous-chefs/mariadb#74]
I'm not sure if its intended or not, but just looking at the recipes it seems that the standard server recpie has some features that are not avalible to the galera recipe.

Things like:
- [ ] [moving the data_dir](https://github.com/sinfomicien/mariadb/blob/fb252d794870ae978d3ada36eb358db957e213cb/recipes/server.rb#L50) 
- [ ] [changing the root password after installation](https://github.com/sinfomicien/mariadb/blob/fb252d794870ae978d3ada36eb358db957e213cb/recipes/server.rb#L93)

If these can be added, I will gladly port the features and get any matching tests in place. If these are not supported for galera for some reason can we add an explination to the documentation?

**Comment by sinfomicien** [comment]
For the data_dir... You can't do it easily as your cluster is up & running. If you want to change the data_dir as your cluster is running, it's very tricky... We try to do it here, but never succeed. If you want to challenge yourself, please do a working PR :)

 For the root password, you can port it, probably a miss from my side :) Thx

**Comment by xorima** [comment]
Hi, 
Closing issue as we have released 2.0.0 which does not use recipes anymore, if you are still having an issue please re-open 

Thanks
