### ISSUE TITLE
service is restarted every run if not localhost

### ISSUE THREAD

**Issue by kevsgithub** [sous-chefs/mariadb#76]
setting node.default['mariadb']['mysqld']['bind_address'] causes the service to be restarted on every chef run.

INFO: Processing execute[mariadb-service-restart-needed] action run (mariadb::server line 81)

  only_if do
    mariadb_service_restart_required?(
      '127.0.0.1',
      node['mariadb']['mysqld']['port'],
      node['mariadb']['mysqld']['socket']
    )
  end

Changing '127.0.0.1' to node['mariadb']['mysqld']['bind_address'] works for me, but I'm new to all of this.

**Comment by sinfomicien** [comment]
Seems, you're right... Could you please send a PR ?

**Comment by sinfomicien** [comment]
Will do it, as i need to add it to galera by the way

**Comment by sinfomicien** [comment]
Waiting for PR #78 to pass tests

**Comment by sinfomicien** [comment]
The bug is fixed in the latest mariadb cookbook version. Thx for your bug submission

**Comment by kevsgithub** [comment]
Thank you for your efforts.
