### ISSUE TITLE
mariadb recipe on ubuntu

### ISSUE THREAD

**Issue by lmeyemezu** [sous-chefs/mariadb#80]
I encounter the error below when installing mariadb recipe on ubuntu

tarting Chef Client, version 12.4.0
resolving cookbooks for run list: ["mariadb::server"]
Synchronizing Cookbooks:
- apt
- mariadb
  Compiling Cookbooks...
# 
# Recipe Compile Error
## Chef::Exceptions::RecipeNotFound

could not find recipe default for cookbook apt
## Cookbook Trace:

  /var/chef/cache/cookbooks/mariadb/recipes/repository.rb:11:in `from_file'
  /var/chef/cache/cookbooks/mariadb/recipes/server.rb:29:in`from_file'
## Relevant File Content:

/var/chef/cache/cookbooks/mariadb/recipes/repository.rb:

  4:  when 'redhat', 'centos', 'fedora', 'scientific', 'amazon'
  5:    install_method = 'yum'
  6:  end
  7:
  8:  if node['mariadb']['use_default_repository']
  9:    case install_method
 10:    when 'apt'
 11>>     include_recipe 'apt::default'
 12:
 13:      apt_repository "mariadb-#{node['mariadb']['install']['version']}" do
 14:        uri 'http://' + node['mariadb']['apt_repository']['base_url'] + '/' + \
 15:          node['mariadb']['install']['version'] + '/' +  node['platform']
 16:        distribution node['lsb']['codename']
 17:        components ['main']
 18:        keyserver 'hkp://keyserver.ubuntu.com:80'
 19:        key '0xcbcb082a1bb943db'
 20:      end

Running handlers:
Running handlers complete
Chef Client failed. 0 resources updated in 5.291843573 seconds

**Comment by sinfomicien** [comment]
As the metadata reference the apt cookbook as a dependency... I do not understand. Which version of Ubuntu do you use ? So i can test it. Thx

**Comment by kevsgithub** [comment]
I'm running this cookbook on ubuntu 15.04 with apt cookbook 2.6.1 without any issues.
May I suggest that the original poster forgot/mislaid the apt dependency?

If @lmeyemezu is running a different version of ubuntu I can test.

**Comment by lmeyemezu** [comment]
Hi  nicolas,
sorry for the delay..
apt dependency was effectively forgotten.
The issue can be closed.
Regards

Cordialement,
Meye-Mezu Lylian
Tel.:06 98 93 13 14

2015-08-24 23:53 GMT+02:00 kevsgithub notifications@github.com:

**Comment by sinfomicien** [comment]
Thx for your feedback!
