### ISSUE TITLE
MariaDB 10.1

### ISSUE THREAD

**Issue by Esysteme** [sous-chefs/mariadb#83]
Could you take MariaDB 10.1 in consideration ?

repo for 10.1 are available

**Comment by sinfomicien** [comment]
We are working on it ! We can expose our dev branch if you want to test...

**Comment by Esysteme** [comment]
yeah I would

**Comment by sinfomicien** [comment]
Did not fogot! But a lot of work let me far from working on release my branch. Will try to do it before the end of next month

**Comment by sinfomicien** [comment]
engel75 did a great job... Some tests to fix in master, and docs to adapt. But you can test 10.1 using the master branch now

**Comment by Paladin** [comment]
Not sure if you just didn't notice this was still open, but I've been using the cookbook to install 10.1 from the mariadb servers now for a while, so I think maybe this is closable.

**Comment by shoekstra** [comment]
I'm going to close this one for now. It's possible to install 10.1 by setting `['mariadb']['install']['version'] = '10.0'` and according to @Paladin this is working without error.

In v2.0.0 we will default to installing `10.1`.
