### ISSUE TITLE
Changing ['mariadb']['mysqld']['options'] should restart mariadb

### ISSUE THREAD

**Issue by kevsgithub** [sous-chefs/mariadb#84]
After installing MariaDB I needed to change some msqld options in a recipe. eg.
node.override['mariadb']['mysqld']['options'] = {
  'max_connect_errors' => '100'
}
The update was correctly applied to my.cnf however the service was not restarted.
Tested on '0.3.1'

**Comment by kevsgithub** [comment]
I've checked this again.

```
Recipe: mariadb::config
  * template[/etc/mysql/my.cnf] action create
    - update content in file /etc/mysql/my.cnf from 2af9d8 to 5925b9
    --- /etc/mysql/my.cnf       2015-08-23 21:03:25.999344309 -0400
    -max_connections = 100
    +max_connections = 101
..........
  * mariadb_configuration[innodb] action add
    * template[/etc/mysql/conf.d/innodb.cnf] action create (up to date)
     (up to date)
  * mariadb_configuration[replication] action add
    * template[/etc/mysql/conf.d/replication.cnf] action create (up to date)
     (up to date)
Recipe: mariadb::server
  * service[mysql] action nothing (skipped due to action :nothing)
  * execute[mariadb-service-restart-needed] action run (skipped due to only_if)
  * execute[install-grants] action nothing (skipped due to action :nothing)
  * template[/etc/mariadb_grants] action create (up to date)
Recipe: mariadb::client
  * apt_package[mariadb-client-10.0] action install (up to date)
```

**Comment by mfouilleul** [comment]
It seems to risky to force the restart when attributes are overrided. If you don't use chef environments, all the MySQL could be restarted at the next chef-client run it can be a mess if you don't have planned this scenario. However, we maybe could handle the variable modifications for the DYNAMIC ones with the `set global` command in the recipe.

Currently when we want to change MySQL variables on our production cluster, we do with `set global` directly on our instances, tests if everything goes right. Then, we update our recipes to persist the changes in our`.cnf` files.

Max.

**Comment by kevsgithub** [comment]
I can respect that. Thank you.
One of our apps needs ansi quotes set before it will work. I'll try adding a reboot resource to our install wrapper. We also wouldn't update these settings once the node is running.

I'll close as wont fix.
