### ISSUE TITLE
Node search in galera setup results in excessive log output

### ISSUE THREAD

**Issue by explody** [sous-chefs/mariadb#90]
In galera.rb, after the node search is done, this snippet outputs a log entry (line ~69)

``` ruby
    log 'Chef search results' do
      message "Searching for \"#{node['mariadb']['galera']['cluster_search_query']}\" \
        resulted in \"#{galera_cluster_nodes}\" ..."
    end
```

Which results in the array of galera_cluster_nodes being dumped into the log, including the full structure of node attributes - over 200K of text in our case.

It's possible that we could suppress this with log level tweaking but I'm not sure that 200K of unformatted ruby hash would ever be useful in a log file - plus it could lead to a sensitive data leak depending on what's in the node attributes.

**Comment by shoekstra** [comment]
This has been moved to the debug log, so you shouldn't see this anymore.
