### ISSUE TITLE
Default repository use results in fetching the repo key on every chef-client run

### ISSUE THREAD

**Issue by explody** [sous-chefs/mariadb#91]
This one is fairly important as every maria install using this feature will be hitting the ubuntu keyserver on _every_ run. 

 The apt repository as defined in repository.rb specifies the key as 

```
key '0xcbcb082a1bb943db'
```

But this will never match as the apt cookbook checks for preexisting keys like this:

``` ruby
    not_if do
      key_present = extract_fingerprints_from_cmd('apt-key finger').any? do |fingerprint|
        fingerprint.end_with?(key.upcase)
      end
```

Fingerprint output from 'apt-key finger' is all uppercase and there is no preceding '0x'.  The key should be specified as:

```
key 'CBCB082A1BB943DB'
```

This can be easily confirmed by running the client more than once and watching log output to see that it fetches the key from keyserver.ubuntu.com on every run.  The fix can be tested by removing the apt-key and repo file and re-running chef-client several times.  The key will be imported again on the first run and detected (but not re-added) on subsequent runs.

**Comment by sinfomicien** [comment]
I push a fix as you said (not so late, 8 months is fair ? ;) )
Will create a version with the change, as soon as possible. In the meantime, you can try the master version in this git repo.

**Comment by PowerKiKi** [comment]
Nevermind, I was confused. Sorry for the noise.
