### ISSUE TITLE
MariaDB Not Starting after Chef Installation on Lubuntu

### ISSUE THREAD

**Issue by rodel-talampas** [sous-chefs/mariadb#95]
OS: Lubuntu
MariaDb Version: 10.0

I tried running this recipe and did some overrides of some attributes but i am having this error:
10.6.16.15   \* template[/etc/mysql/debian.cnf] action create
10.6.16.15     - update content in file /etc/mysql/debian.cnf from f9b98e to 751c0c
10.6.16.15     - suppressed sensitive resource
10.6.16.15   \* execute[correct-debian-grants] action run[2016-02-12T15:33:23+08:00] ERROR: execute[correct-debian-grants](mariadb::galera line 143) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
10.6.16.15 ---- Begin output of mysql -r -B -N -u root --password='tln123' -e "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON  _._ TO 'tln'@'localhost' IDENTIFIED BY 'tln123' WITH GRANT OPTION" ----
10.6.16.15 STDOUT: 
10.6.16.15 STDERR: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/home/tln/mysqld/mysqld.sock' (2 "No such file or directory")
10.6.16.15 ---- End output of mysql -r -B -N -u root --password='tln123' -e "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON  _._ TO 'tln'@'localhost' IDENTIFIED BY 'tln123' WITH GRANT OPTION" ----
10.6.16.15 Ran mysql -r -B -N -u root --password='tln123' -e "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON  _._ TO 'tln'@'localhost' IDENTIFIED BY 'tln123' WITH GRANT OPTION" returned 1; ignore_failure is set, continuing

*_### -- It seems that the mariadb server was not running. *_

When i ran manually, error:

Failed to open file '/var/lib/mysql//galera.cache' : 13 (Permission Denied)

Not sure but, it seems this is a permission problem. this directory belongs to mysql but I did not or can't find any in the recipe that created a mysql user. Or probably another user it seems. 
# 

Installing Manually (MariaDB-Galera-Server) works seemlessly on my END.

**Comment by shoekstra** [comment]
That is interesting as I would expect Lubuntu to operate the same way Ubuntu does, and we fully support Ubuntu.

I'll take a look into this and see if I can resolve it before the next release.

**Comment by shoekstra** [comment]
I was able to replicate the problem.

When converging for the first time Chef fails, second time it failed too, I logged in and manually started the mysql service and then was able to converge successfully.

**Comment by xorima** [comment]
Hi, 
Closing issue as we have released 2.0.0 which does not use recipes anymore, if you are still having an issue please re-open 

Thanks
